import json

with open('/tmp/video-quotes/NApOvFHCb8s/summary.json') as f:
    summary = json.load(f)

title = summary['title']
vid = summary['videoId']
quotes = summary['quotes']

html = f"""<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif;
      background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
      min-height: 100vh;
      color: #fff;
      padding: 24px 16px;
    }}
    header {{
      text-align: center;
      margin-bottom: 32px;
      padding: 24px;
      background: rgba(255,255,255,0.05);
      border-radius: 16px;
      border: 1px solid rgba(255,255,255,0.1);
    }}
    header h1 {{ font-size: clamp(1.1rem, 2.5vw, 1.6rem); margin-bottom: 12px; }}
    header .meta {{ color: #a1a1aa; font-size: 0.95rem; margin-bottom: 16px; }}
    header a {{ color: #60a5fa; text-decoration: none; display: inline-flex; align-items: center; gap: 6px; padding: 8px 16px; background: rgba(96,165,250,0.1); border-radius: 8px; transition: 0.2s; }}
    header a:hover {{ background: rgba(96,165,250,0.2); }}
    .gallery {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 24px; max-width: 1400px; margin: 0 auto; }}
    .card {{ background: rgba(255,255,255,0.03); border-radius: 16px; overflow: hidden; border: 1px solid rgba(255,255,255,0.05); cursor: pointer; transition: 0.3s; }}
    .card:hover {{ transform: translateY(-4px); border-color: rgba(255,255,255,0.2); background: rgba(255,255,255,0.05); }}
    .card img {{ width: 100%; aspect-ratio: 16/9; object-fit: cover; display: block; }}
    .card .content {{ padding: 16px; }}
    .card .timecode {{ font-family: ui-monospace, monospace; color: #9ca3af; font-size: 0.85rem; margin-bottom: 8px; display: inline-block; padding: 4px 8px; background: rgba(0,0,0,0.3); border-radius: 6px; }}
    .card .text {{ color: #e5e7eb; font-size: 0.95rem; line-height: 1.6; word-break: break-all; }}
    footer {{ text-align: center; margin-top: 48px; padding: 24px; color: #6b7280; font-size: 0.9rem; }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <div class="meta">共 {len(quotes)} 句金句</div>
    <a href="https://youtu.be/{vid}" target="_blank">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"/></svg>
      觀看原影片
    </a>
  </header>
  
  <div class="gallery">
"""

for i, q in enumerate(quotes):
    # timecode is like "00:01:23,000 --> 00:01:25,000", convert to seconds for youtube link
    tc = q['timecode'].split(' --> ')[0]
    parts = tc.split(',')[0].split(':')
    sec = int(parts[0])*3600 + int(parts[1])*60 + int(parts[2])
    
    html += f"""
    <div class="card" onclick="window.open('https://youtu.be/{vid}?t={sec}s', '_blank')">
      <img src="quote_{i+1:02d}.jpg" alt="Keyframe">
      <div class="content">
        <div class="timecode">{tc.split(',')[0]}</div>
        <div class="text">{q['tgt']}</div>
      </div>
    </div>
"""

html += """
  </div>
  <footer>Generated by OpenClaw</footer>
</body>
</html>
"""

with open('/tmp/video-quotes/NApOvFHCb8s/index.html', 'w') as f:
    f.write(html)
